#! /bin/sh

# sudo localedef -f UTF-8 -i de_AT de_AT.UTF-8

xsetroot -cursor_name left_ptr
sxhkd &

polybar rome -r &

feh --bg-fill $HOME/.backgrounds/wallpaper.png

mount ~/org/nas &

# sh ~/.config/bspwm/fehbg

# xrdb -merge ~/.Xresources

$HOME/bin/nasa_bg.sh &

# mpd &

nm-applet &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# compton --config ~/.config/compton.conf &

udiskie -a -t -F &

/usr/bin/synergy &

fcitx -rd &

dunst -fn Noto sans 12 &

google-chrome --restore-last-session &

/usr/bin/davmail $HOME/dotfiles/davmail/davmail.properties &
thunderbird &

bspc monitor -d web mail editor terminal tor VI VII VIII IX X

bspc config border_width        3
bspc config normal_border_color "#b5b49c"
bspc config active_border_color "#b5b49c"
bspc config focused_border_color "#213b59"
bspc config window_gap          0
bspc config single_monocle      true
bspc config borderless_monocle	true

bspc config split_ratio                 0.5
bspc config focus_follows_pointer       true

bspc config click_to_focus any

# Alt+drag to move floating window Alt+rightdray to resize
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc rule -a "Google-chrome" desktop=web
bspc rule -a Thunderbird desktop=mail
bspc rule -a Emacs desktop=editor follow=on state=tiled
bspc rule -a "Tor Browser" desktop=tor
bspc rule -a "Pidgin" desktop=VI

## need to be floating
bspc rule -a Audacious state=floating follow=on
bspc rule -a Conky state=floating follow=on
bspc rule -a Viewnior state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Gpicview state=floating follow=on
bspc rule -a L3afpad state=floating follow=on
bspc rule -a Leafpad state=floating follow=on
bspc rule -a Gnome-calculator state=floating follow=on
bspc rule -a Gparted state=floating follow=on
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Preferences state=floating follow=on
bspc rule -a dialog state=floating follow=on
bspc rule -a menu state=floating follow=on
bspc rule -a pop-up state=floating follow=on
bspc rule -a task_dialog state=floating follow=on
bspc rule -a bubble state=floating follow=on
bspc rule -a Places state=floating follow=on
bspc rule -a Biblioteca state=floating follow=on
bspc rule -a 'Seleccionar un archivo' state=floating follow=on
bspc rule -a Confirm state=floating follow=on
bspc rule -a Confirmar state=floating follow=on
bspc rule -a 'Acerca de Mozilla Firefox' state=floating follow=on
bspc rule -a 'About Mozilla Firefox' state=floating follow=on
bspc rule -a 'Buscar archivos' state=floating follow=on
